### ISSUE TITLE
The remote server returned an error: (503) Service Temporarily Unavailable.

### ISSUE THREAD

**Issue by kculwpvalxe** [Vauff/MapDownloader#3]
![image](https://user-images.githubusercontent.com/13507066/79036786-1dcb6500-7bfe-11ea-9623-b772c837919b.png)
I think downloader got blocked by GFLclan Cloudflare service
![image](https://user-images.githubusercontent.com/13507066/79036808-5a975c00-7bfe-11ea-8834-85fb4e14a562.png)

**Comment by Vauff** [comment]
This isn't a bug with the program, since this does not happen normally

However I'll leave this open, since I believe CloudFlare may be flagging your IP for some reason and performing browser validation for DDOS protection. Which therefore causes the download to fail.

May I ask, have you also been unable to download via our FastDL ingame? And how long has this been occuring (and is it still happening now)?

**Comment by kculwpvalxe** [comment]
![20200411224238_1](https://user-images.githubusercontent.com/13507066/79046847-ca7d0500-7c45-11ea-8e71-48bd55e68f20.jpg)
![20200411224310_1](https://user-images.githubusercontent.com/13507066/79046855-d49f0380-7c45-11ea-84ef-6ef343ba3283.jpg)

I can't download map via FastDL in game. I just download csgo and play on GFL ZE server yesterday.
Last time I played on server and able to download map is around last year October

![image](https://user-images.githubusercontent.com/13507066/79046980-8a6a5200-7c46-11ea-9ed9-5ace208275b0.png)
I can download map through browser, cloudflare show up a few times when download first few map.
After downloaded 7 maps, cloudflare didn't show up, straight to download prompt;

**Comment by Vauff** [comment]
Can you add me on Discord @Vauff#2804? Would like some private info if you can provide it

**Comment by Vauff** [comment]
Added a temporary workaround for this by adding an alternative FastDL link in the program https://github.com/Vauff/MapDownloader/commit/83eb9af7452ab8ab4b0a60a2e2d025d507bfed2d
